language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

services:
   - mysql
before_install:
  - mysql -e 'CREATE DATABASE usersDB;'

notifications:
  email:
    - lam@cphbusiness.dk
script:
  - mvn verify


